

spring:
  data:
    cassandra:
      keyspace-name: main
      username: PkZhCReUWahfrKlQsCPPoUkh
      password: BfgnppCWB-MLHc_.rII,rSyq6cPqLGO0c4+bGkZ9rSzs9khQorQNU-C,3hR+EijiTZ33NL_yFeCjuYgUxXtmBwFeDNmg6z5do5o6wq4KiCRxtxw,3mTmI5jrc52BUasn
      schema-action: recreate_drop_unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.9785222cbf164dcb
            client-secret: 4a4e840e28eaa41e36c7da91e79772062dabbb2d

datastax.astra:
  secure-connect-bundle: secure-connect-mailbox.zip

#Connecting Cassandra Database
astra:
  db:
    id: 062287ff-f529-4ec7-8163-7672225ba275
    region: asia-south1
    keyspace: main
    application:
      token: AstraCS:PkZhCReUWahfrKlQsCPPoUkh:a0f30126b995ffde6ced514ad899d5bddcd202b49e2e4d96335b0b0a0dbf7ba4