

spring:
  data:
    cassandra:
      keyspace-name: main
      username: YOUR_USER_NAME
      password: YOUR_PASSWORD
      schema-action: recreate_drop_unused
      request:
        timeout: 11s
      connection:
        connect-timeout: 11s
        init-query-timeout: 11s
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET


datastax.astra:
  secure-connect-bundle: secure-connect-mailbox.zip

#Connecting Cassandra Database
astra:
  db:
    id: 062287ff-f529-4ec7-8163-7672225ba275
    region: asia-south1
    keyspace: main
    application:
      token: YOUR_ASTRA_TOKEN
